refactor: simplify invocation with argument
only allow one argument at a time

diff --git a/commitlint b/commitlint
--- a/commitlint
+++ b/commitlint
@@ -12,13 +12,13 @@
 set -eu
 
 error() {
-	printf 'ERROR: "%s" - %s\n' "$(head -n1 "$SRC")" "$@" >&2
+	printf 'ERROR: "%s" - %s\n' "$(head -n1 "$SUBJECT")" "$@" >&2
 	exit 1
 }
 
 lint() {
 	pattern="$1"
-	head -n1 "$SRC" | grep -q -E "$pattern"
+	head -n1 "$SUBJECT" | grep -q -E "$pattern"
 }
 
 if [ -p /dev/stdin ]; then
@@ -26,36 +26,37 @@ if [ -p /dev/stdin ]; then
 	f="$(mktemp)" && trap 'rm $f' 0
 	cat /dev/stdin >"$f"
 	set -- "$f"
-elif [ "$#" -gt 0 ]; then
-	:
+elif [ "$#" -eq 1 ]; then
+	# pipe the argument into ourself
+	printf '%s' "$1" | "$0"
+	exit $?
 else
 	error "Invalid input"
 fi
 
-for f; do
-	SRC="$f"
+# global file reference used by lint()
+SUBJECT="$f"
 
-	# custom rules
-	lint "^initial commit$" && continue
-	lint '^Revert ".+"' && continue
+# custom rules
+lint "^initial commit$" && exit
+lint '^Revert ".+"' && exit
 
-	# https://github.com/conventional-changelog/commitlint/tree/b12ec06/%40commitlint/config-conventional
+# https://github.com/conventional-changelog/commitlint/tree/b12ec06/%40commitlint/config-conventional
 
-	scope="(|\([[:alnum:]\/_-]+\))"
+scope="(|\([[:alnum:]\/_-]+\))"
 
-	## type
-	lint "^[a-zA-Z]+.*:" || error "missing TYPE. use '{TYPE}: {SUBJECT}'"
-	lint "^[a-z]+.*:" || error "TYPE needs to start with lowercase word"
-	lint "^(build|chore|ci|docs?|feat|fix|perf|refactor|revert|style|tests?)[^[:alnum:]]+" || error "invalid TYPE"
+## type
+lint "^[a-zA-Z]+.*:" || error "missing TYPE. use '{TYPE}: {SUBJECT}'"
+lint "^[a-z]+.*:" || error "TYPE needs to start with lowercase word"
+lint "^(build|chore|ci|docs?|feat|fix|perf|refactor|revert|style|tests?)[^[:alnum:]]+" || error "invalid TYPE"
 
-	# breaking indicator
-	lint "^[a-z]+(|\(.*\))(|!):" || error "Breaking Indicator malformed"
+# breaking indicator
+lint "^[a-z]+(|\(.*\))(|!):" || error "Breaking Indicator malformed"
 
-	## scope
-	lint "^[a-z]+${scope}(|!):" || error "SCOPE malformed"
+## scope
+lint "^[a-z]+${scope}(|!):" || error "SCOPE malformed"
 
-	## subject
-	lint "^[a-z]+.*: [a-z]" || error "SUBJECT needs to start with lowercase word"
-	lint "^[a-z]+.*: [a-z].{2,}" || error "SUBJECT is expected to be at least 3 chars"
-	lint "[^\.]$" || error "SUBJECT should not end with full-stop"
-done
+## subject
+lint "^[a-z]+.*: [a-z]" || error "SUBJECT needs to start with lowercase word"
+lint "^[a-z]+.*: [a-z].{2,}" || error "SUBJECT is expected to be at least 3 chars"
+lint "[^\.]$" || error "SUBJECT should not end with full-stop"
